Asyncify running password prompt dialog.
This makes it actually show up. It actually shows up twice, because
gtimelog makes two requests on startup... and the second time the
callback throws:

    Traceback (most recent call last):
      File "./src/gtimelog/gtimelog.py", line 854, in on_response
        username = userentry.get_text ()
    NameError: free variable 'userentry' referenced before assignment in enclosing scope

Which is weird because it's not true, but hey.